# Generated by Django 4.2.6 on 2024-02-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='topic',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default=6, max_length=200),
            preserve_default=False,
        ),
    ]
